name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master, dev ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
      # Installs the dotnet version specified in global.json
      - name: Build
        run: |
          dotnet build
      - name: Test
        run: |
          dotnet test
