name: Publish

on:
  push:
    tags:
        - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Build
        run: |
          dotnet publish -c Release
      - name: Push
        run: |
          dotnet nuget push "OAuth2Authenticator/bin/Release/OAuth2Authenticator.*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
